version: '3'

networks:
    sorteiovirtualshop:

services:

    # nginx
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-sorteiovirtualshop
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74
            - mysql8
        networks:
            - sorteiovirtualshop

    # php
    php74:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php74-sorteiovirtualshop
        ports:
            - "9000:9000"
        volumes:
            - ./src:/var/www/html
        networks:
            - sorteiovirtualshop

    # mysql
    mysql8:
        #image: mysql:8.0
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        container_name: mysql8-sorteiovirtualshop
        ports:
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sorteiovirtualshop_ecom
            MYSQL_USER: commerce_user
            MYSQL_PASSWORD: ksjdpo71521
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        restart: always

    # phpmyadmin
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin-sorteiovirtualshop
        links:
            - mysql8
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql8
        networks:
            - sorteiovirtualshop